name: Send GET Request
on:
  schedule:
    - cron: '*/7 * * * *'
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET Request
        run: |
          curl habit-tracker-bvzb.onrender.com
